### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'attachments'

### ISSUE THREAD

**Issue by Doezer** [Djones4822/pyTeamUp#9]
I've got this error while trying a simple, no arguments, get_event_collection.

Here's the code

```
# Instantiate the calendar
        calendar = Calendar(program_variables.calendar_id, program_variables.api_key)
        cast_unavailabilities = []
        prod_unavailabilities = []

        # Gather Event Collections (returns a list)
        start_date_string = '2021-11-24 18:00'
        end_date_string = '2021-11-24 22:00'
        start_date = datetime.strptime(start_date_string, '%Y-%m-%d %H:%M')
        end_date = datetime.strptime(end_date_string, '%Y-%m-%d %H:%M')

        logging.info(f'Indispos de {start_date_string} à {end_date_string}')

        event_list = calendar.get_event_collection(start_dt=start_date, end_dt=end_date)
```

and the error

```
Traceback (most recent call last):
  File "G:/Prog/Git/cn-discord-bot/teamUp.py", line 61, in <module>
    event_list = calendar.get_event_collection()
  File "G:\Prog\Git\personal-shit\venv\lib\site-packages\pyteamup\Calendar.py", line 116, in get_event_collection
    return [Event(self, **event_dict) for event_dict in self.events_json]
  File "G:\Prog\Git\personal-shit\venv\lib\site-packages\pyteamup\Calendar.py", line 116, in <listcomp>
    return [Event(self, **event_dict) for event_dict in self.events_json]
TypeError: __init__() got an unexpected keyword argument 'attachments'
```

**Comment by Djones4822** [comment]
Fixed with version 0.1.4a, available on pip for upgrade. Thanks @LogicallyUnfit!

**Comment by LogicallyUnfit** [comment]
Glad to help!

**Comment by Doezer** [comment]
Thanks!
